transport_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: warehouse
      user: admin
      password: senha_secreta
      port: 5432
      dbname: transport_dw
      schema: dbt_aluno
      threads: 4